### ISSUE TITLE
How to use with jwilder/nginx-proxy

### ISSUE THREAD

**Issue by ghost** [meteorhacks/meteord#46]
Hi guys,

sorry for the maybe simple question, but how to make the meteorD image work with jwilder/nginx-proxy if I am already using it in my setup.. 

Is anyone familiar with it?

**Comment by jshimko** [comment]
You just need to add the `VIRTUAL_HOST` environment variable to your Meteor container and `jwilder/nginx-proxy` will forward requests to that domain name to your app.

**Comment by ghost** [comment]
@jshimko thanks. So no changes to the port or so.. nothing? I mean the -p stay 8080:80 like in the description?

**Comment by jshimko** [comment]
No ports need to be explicitely opened to the host on your app container (as in `-p 8080:80`).  A port just needs to be [exposed](https://docs.docker.com/reference/builder/#expose).  And that's already taken care of in meteord by its Dockerfile.  So skip the `-p` arg if you're using `jwilder/nginx-proxy`.

`jwilder/nginx-proxy` will automatically detect the only internally exposed port (80 in this case) and send traffic there.  But note that if you have more than one port open on your Meteor app container (probably not), you'd also have to set the `VIRTUAL_PORT` environment variable as well.  If you're using meteord in the typical way, that env var can be skipped.

So launch nginx as mentioned in the docs:

``` sh
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

Then launch your Meteor app with the VIRTUAL_HOST env var set.

``` sh
docker run -d  \
  -e MONGO_URL="" \
  -e MONGO_OPLOG_URL="" \
  -e MAIL_URL="" \
  -e ROOT_URL="http://example.com" \
  -e VIRTUAL_HOST="example.com" \
  myname/myapp
```

`jwilder/nginx-proxy` will automatically detect your app and requests to `http://example.com` will then get routed there.  Your app container also won't be accessible to the world directly because no ports were opened to the host - only _exposed_ within Docker.  This setup is also a great option for SSL termination.  (see the jwilder/nginx-proxy README for SSL setup details)

You could then launch any amount of additional apps on the same host with a `VIRTUAL_HOST` environment variable set and nginx will route to them based on the domain name (assuming all of these domain names point to that host IP, of course).

Make sense?

**Comment by ghost** [comment]
Oh yeah, it make sense. I am heaving some other issues with the mongo url (also dockerized) so I couldn't test the setup properly yet. But now I have the understanding how it works, thank you very much for the precise answer!

**Comment by ghost** [comment]
It, worked. Thank you!

**Comment by jujes** [comment]
@jshimko what if I'm running reaction commerce? 
I get: **502 Bad Gateway
nginx/1.9.12**

**docker-compose.yml**

```
reaction:
  restart: always
  image: reactioncommerce/reaction
  links:
    - mongo
  ports:
    - 80
  container_name: reaction
  environment:
    - VIRTUAL_HOST=reaction.dev
    - ROOT_URL=http://reaction.dev
    - MONGO_URL=mongodb://mongo:27017/reaction
    - REACTION_EMAIL=admin@admin.com
    - REACTION_USER=admin
    - REACTION_AUTH=password
mongo.rootsoap:
  restart: always
  image: mongo:2.6.11
  command: mongod --smallfiles
  container_name: mongo
```

**deploy script:**

```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
docker-compose -f docker/docker-compose.yml up -d

```

**Comment by jshimko** [comment]
@jujes well, my first guess is you can't open port 80 on two containers on the same host (it looks like you have it open on nginx and Reaction).  Remove the `ports:` lines from your docker-compose config.

``` sh
# start nginx
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

``` yaml
# docker-compose.yml
reaction:
  image: reactioncommerce/reaction:latest
  links:
    - mongo
  environment:
    - VIRTUAL_HOST=reaction.dev
    - ROOT_URL=http://reaction.dev
    - MONGO_URL=mongodb://mongo:27017/reaction
    - REACTION_EMAIL=admin@admin.com
    - REACTION_USER=admin
    - REACTION_AUTH=password
mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
```

``` sh
# start Reaction
docker-compose up -d
```

And for future reference, when you have startup issues like this, you should check the container logs for more info.  You likely would have seen something in the Reaction container startup logs about the port conflict.  You can run `docker-compose logs -f <container name>` to watch the logs.  Using the file above, it would be `docker-compose logs -f reaction`.  (or just `docker-compose logs -f` to see the logs of everything in your `docker-compose.yml` file.
