### ISSUE TITLE
Error: failed to connect to [mongo-dev:27017] using docker-compose

### ISSUE THREAD

**Issue by bwhitty** [meteorhacks/meteord#54]
My `Dockerfile` is as follows:

```
FROM meteorhacks/meteord:onbuild
```

My `docker-compose.yml` is as follows:

``` yaml
hub:
    image: ...
    restart: always
    ports: 
        - "3000:80"
    volumes:
        - ...
    links:
        - mongo-dev:mongo-dev
    environment:
        - MONGO_URL=mongodb://mongo-dev/hub
        - ROOT_URL=http://...
        - DELAY=30
        - 'METEOR_SETTINGS={ ... }'
    log_driver: "json-file"
    log_opt:
        max-size: "20m"
        max-file: "3"
mongo-dev:
    image: mongo:2.6.11
    restart: always
    ports:
        - "27017:27017"
    log_driver: "json-file"
    log_opt:
        max-size: "20m"
        max-file: "3"
```

It appears that the delay is not being honored, as I see the meteor container boot just as fast if not faster than the mongo container, which then fails with 

```
hub_1       | /built_app/programs/server/node_modules/fibers/future.js:278
hub_1       |                       throw(ex);
hub_1       |                             ^
hub_1       | Error: failed to connect to [mongo-dev:27017]

...

dockerhub_hub_1 exited with code 0
```

I do not see https://github.com/meteorhacks/meteord/blob/master/base/scripts/run_app.sh#L36 echoed to the command line. The code appears correct, so this leads me to believe that `meteord:base` image has not been updated at docker.io. Can you verify?
