### ISSUE TITLE
What is the point of devbuild?

### ISSUE THREAD

**Issue by ndarilek** [meteorhacks/meteord#57]
Maybe I'm missing something obvious?

I wanted to launch my Meteor stack from docker-compose rather than the command line tool. I.e. docker-compose would use the meteor command directly, but it would link to a separate mongo plus other services I need for my app. My code directory would be bind-mounted into /app, and docker-compose would basically replace the locally-run meteor command, giving me the ability to spin up and monitor something like postgres instead of mongo.

I'd have expected devbuild to accomplish this, only it removes the local meteor install on its way out. I can certainly reinstall it myself, but what is the point of devbuild if it does this? I get that it behaves a bit differently, but under what scenarios would I want to use devbuild vs. onbuild? I.e. not "it downloads Meteor every time," but what practical benefit does this distinction serve as implemented? My expectation is that devbuild leaves the local install in place so I can use it for development in cases where I need to spin up dependent services and want to do so as part of a single-command launch.

Thanks.

**Comment by jshimko** [comment]
`devbuild` is used when you don't want to install Meteor _every_ time you build your container.  It saves you several minutes of build time each time.

**Comment by ndarilek** [comment]
So when would you use it? I could understand if it included the meteor 
CLI tool, but it doesn't, or didn't when I last checked.

**Comment by jakobrosenberg** [comment]
onbuild and devbuild Dockerfiles seem practically identical if you look at on_build.sh.

Devbuild

```
ONBUILD RUN bash $METEORD_DIR/lib/install_meteor.sh
ONBUILD COPY ./ /app
ONBUILD RUN bash $METEORD_DIR/lib/build_app.sh
```

Onbuild

```
ONBUILD COPY ./ /app
ONBUILD RUN bash $METEORD_DIR/on_build.sh
```

on_build.sh

```
#!/bin/bash
set -e

bash $METEORD_DIR/lib/install_meteor.sh
bash $METEORD_DIR/lib/build_app.sh
```

**Comment by romant** [comment]
Just looked through it (the devbuild), as am using the `meteorhacks/meteord:onbuild` for actual deployment. Was hopeful of to use docker-compose overlays to put together a **dev** specific configuration.

I was under the impression that the `:devbuild` was to run local instances of meteor; as I believe @ndarilek is alluding to.

Looks like it's there purely for to save on a few seconds of build time. As executing mere `meteor` within, will show you that plenty doesn't work for meteor **run** out of the box; and its too minimal for mongo to work out of the box as well.

I'll look at extending its config to allow me to do the described; unless someone's already done it?

As would like to use the same effective base for what is going to end up in production as well.

**Comment by athyuttamre** [comment]
Yeah, @arunoda, it would be nice to bind-mount the codebase when running `:devbuild` so that we can actually use it for local development.

One of the fundamental ideas of Docker is that if it works on your computer, it'll work on the server. To enable this to happen, locally running the app should happen _within_ Docker.

@romant did you ever get down to writing that fork?

**Comment by athyuttamre** [comment]
Hey folks, I've submitted a pull request with a bind-mounting version: `meteord:volbuild`.

https://github.com/meteorhacks/meteord/pull/77

**Comment by flippyhead** [comment]
I commented on your pull request but wanted to echo my praise here for this approach. It's either this or Vagrant and I personally prefer Docker.

**Comment by athyuttamre** [comment]
Thanks for backing it up, @flippyhead! I've gone ahead and used `volbuild` in my workflow, and it's been working well for the last 2 months. I hope it gets merged officially!

**Comment by ndarilek** [comment]
I keep wishing some tag of this image included the `meteor` command, particularly now that 1.3 supports testing more fully. It'd be nice to have an image that let me run my tests on my CI server. Is there no way to do that with this image? I know there's a PR, I'm just surprised it hasn't been merged.

**Comment by athyuttamre** [comment]
@ndarilek Yeah, it's unfortunate that the devs haven't responded to the PR either. You can use `athyuttamre/meteord:volbuild` for now if you wish.

**Comment by jshimko** [comment]
@ndarilek why can't you run tests on CI?  That doesn't need to have anything to do with your Docker build.  You can install (and optionally cache) Meteor/NPM on the CI box and then run your tests with it outside of Docker just like you would on your local machine.  Then build the Docker container if the tests pass (since you probably don't want to waste your time building a container from an app with failing tests).

For example, on Circle CI...

``` yaml
machine:
  node:
    version: 0.10.43

  services:
    - docker

dependencies:

  cache_directories:
    - "~/.meteor"
    - "~/.npm"
    - "~/docker"

  override:
    # symlink Meteor to /usr/local/bin if it's cached from an earlier build
    - if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi

    # or install it if it isn't
    - if [ ! -e ~/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

    # install NPM deps for your app
    - meteor npm install

    # run your tests
    - meteor npm run my-tests

    # if they pass, build a Docker image.
    # first, grab the image cache if it exists
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi

    # build container
    - docker build -t yourapp .

    # save cache for next time
    - mkdir -p ~/docker; docker save yourapp > ~/docker/image.tar

    # optionally provide a docker-compose.yml file to do curl tests on your app
    - docker-compose up -d; sleep 20
    - curl --retry 10 --retry-delay 5 -v http://localhost    
```
