### ISSUE TITLE
dfmedia/meteor-mongo not found

### ISSUE THREAD

**Issue by brentjanderson** [meteorhacks/meteord#59]
This docker image is not found on the docker hub.

Thanks, Arunoda & team, for producing such excellent products!

**Comment by jakobrosenberg** [comment]
Same issue for me.

**Comment by jshimko** [comment]
See #68 

Just replace that mongo container with `mongo:latest`.

Example config...

``` yaml
dashboard:
  image: yourrepo/yourapp
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
```
