### ISSUE TITLE
How to set meteor environment variables?

### ISSUE THREAD

**Issue by JulianKingman** [meteorhacks/meteord#80]
I'm trying to ignore Spiderable's continuous SSL errors (per here: https://github.com/meteor/meteor/issues/1837), for which I need to set a meteor environment variable. Where would I set an environment variable such as this?
`'METEOR_PKG_SPIDERABLE_PHANTOMJS_ARGS=--ssl-protocol=tlsv1 --ignore-ssl-errors=yes --debug=true'`
I tried adding that as a docker compose environment variable, but I don't think it worked (should it?).

**Comment by JulianKingman** [comment]
I'm still wondering how to do this, this time for a different situation where I want to create an environment variable for separate subdomains. Any chance you could explain how to do this? I'm using the docker-compose option to build.

**Comment by jshimko** [comment]
``` yaml
dashboard:
  image: yourrepo/yourapp
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   - MAIL_URL=smtp://some.mailserver.com:25
   - METEOR_PKG_SPIDERABLE_PHANTOMJS_ARGS="--ssl-protocol=tlsv1 --ignore-ssl-errors=yes --debug=true"
mongo:
  image: mongo:latest
```

https://docs.docker.com/compose/compose-file/#environment
