### ISSUE TITLE
 `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by yolo1995** [meteorhacks/meteord#86]
hi,

```
meteor_1 |
meteor_1 | /built_app/programs/server/node_modules/fibers/future.js:245
meteor_1 |                                              throw(ex);
meteor_1 |                                                    ^
meteor_1 | Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /built_app/programs/server/npm/vmcloud_media-info/node_modules/mediainfo/node_modules/node-expat/build/Release/node_expat.node)
meteor_1 |     at Module.load (module.js:356:32)
meteor_1 |     at Function.Module._load (module.js:312:12)
meteor_1 |     at Module.require (module.js:364:17)
meteor_1 |     at require (module.js:380:17)
meteor_1 |     at Object.<anonymous> (/built_app/programs/server/npm/vmcloud_media-info/node_modules/mediainfo/node_modules/node-expat/lib/node-expat.js:4:13)
meteor_1 |     at Module._compile (module.js:456:26)
meteor_1 |     at Object.Module._extensions..js (module.js:474:10)
meteor_1 |     at Module.load (module.js:356:32)
meteor_1 |     at Function.Module._load (module.js:312:12)
meteor_1 |     at Module.require (module.js:364:17)
```

i try to : 

```
RUN apt-get update
RUN apt-get -y install libc6
```

but dosnt work. i probably miss something but what ? 

my docker-compose : 

```
meteor:  
  image: PartyProject
  ports:
    - "80:80"
  links:
    - mongo
  environment:
    - MONGO_URL=mongodb://mongo/anything
    - ROOT_URL=http://ip
mongo:  
  image: mongo
  ports:
    - "27017:27017"
```

Yours faithfully
